### ISSUE TITLE
Pythonicism

### ISSUE THREAD

**Issue by ghost** [obhalerao/AES-DES-Project#2]
On [line 36 of aes.py](https://github.com/obhalerao/AES-DES-Project/blob/master/aes.py#L36), you use a bunch of if statements.

1. They shouldn't have parentheses around them. This is Python, not Java.
2. There should be an explicit `return None`/`raise Exception` statement at the end of the function.
3. It's more Pythonic (and potentially faster) to use a dictionary as a lookup. Ex: `return {2: 0, 3: 1, 9: 2, 11: 3, 13: 4, 14: 5}[x]`/`return {2: 0, 3: 1, 9: 2, 11: 3, 13: 4, 14: 5}.get(x, None)`. Or you could just say `mult_hash = {2: 0, 3: 1, 9: 2, 11: 3, 13: 4, 14: 5}.__getitem__` (equivalent to the first option above).

**Comment by ghost** [comment]
Or you could use `return (2, 3, 9, 11, 3, 13, 14).index(x)`/`mult_hash = (2, 3, 9, 11, 13, 14).index`. This would be even faster because I'm sure it's faster to search a list than a dict.

**Comment by obhalerao** [comment]
Actually, i'm pretty sure the .index(x) method for a list is O(n), as it searches the entire list until it finds the element. A dict uses hashing (I think) to increase the efficiency of access to O(1).
But this project is not about efficiency, and I'm too lazy to change the code. So, I'm closing this issue. Moose, stop trolling on my school projects.
